/* Dashboard*/ 

export const GET_PRODUCTS= "GET_PRODUCTS"
export const GET_PRODUCTS_SUCCESS= "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_ERROR= "GET_PRODUCTS_ERROR"

export const GET_MENUS= "GET_MENUS"
export const GET_MENUS_SUCCESS= "GET_MENUS_SUCCESS"
export const GET_MENUS_ERROR= "GET_MENUS_ERROR"

export const ADD_TO_CART = "ADD_TO_CART";
export const SHOW_PRODUCTS_IN_CART = "SHOW_PRODUCTS_IN_CART";
export const HIDE_PRODUCTS_IN_CART = "HIDE_PRODUCTS_IN_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const LOGIN_BUTTON_ACTION = "LOGIN_BUTTON_ACTION";

export const SET_PRODUCTS = "SET_PRODUCTS";



export * from "./my-product/actions";
